### ISSUE TITLE
Test - Code coverage

### ISSUE THREAD

**Issue by sivsivsree** [sivsivsree/routerarc#9]
Code unit testing is not implemented yet.

It is appreciated if the test cases are in [Table driven](https://github.com/golang/go/wiki/TableDrivenTests)

**Comment by ramisback** [comment]
Hi,
Can you elaborate this issue, may be i can contribute

**Comment by sivsivsree** [comment]
> Hi,
> Can you elaborate this issue, may be i can contribute

Hi there, the code does not have any unit test cases right now.
